services = {
    "Airbnb": "uk",
    "Avito": "av",
    "Discord": "ds",
    "eBay": "dh",
    "Facebook": "fb",
    "Google, Youtube, Gmail": "go",
    "Hily": "hily",
    "IMO messenger": "im",
    "Instagram": "ig",
    "KakaoTalk": "kt",
    "Line Messenger": "me",
    "Microsoft": "mm",
    "Naver": "nv",
    "Netflix": "nf",
    "Ok.ru": "ok",
    "Papara": "zr",
    "PayPal": "ts",
    "POF": "pf",
    "Steam": "mt",
    "Telegram": "tg",
    "Tinder": "oi",
    "Twitter": "tw",
    "Viber": "vi",
    "Vk.com": "vk",
    "Whatsapp": "wa",
    "Yalla": "yl",
    "Yahoo": "mb",
    "Yandex": "ya"
}
